version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.1
      - test-2.0
jobs:
  test-1.1:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.Cache -f netstandard1.4
      - run: dotnet build src/LaunchDarkly.Cache -f netstandard1.6
      - run: dotnet test test/LaunchDarkly.Cache.Tests/LaunchDarkly.Cache.Tests.csproj -f netcoreapp1.1
  test-2.0:
    docker:
      - image: microsoft/dotnet:2.0-sdk-jessie
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build src/LaunchDarkly.Cache -f netstandard2.0
      - run: dotnet test test/LaunchDarkly.Cache.Tests/LaunchDarkly.Cache.Tests.csproj -f netcoreapp2.0
